### PR TITLE
Add support for structured logging

### PR DESCRIPTION
**Pull request by MaceWindu**
Example (we use serilog + seq):
image

### CODE REVIEW

**Comment by MaceWindu** [comment]
I wasn't touching console app logging, as you cannot pass logger to it

**Comment by MaceWindu** [comment]
@Sicos1977, could you please release new version?

**Comment by Sicos1977** [comment]
For what? The latest release is 4.2.2 and should have all changes in it --> https://www.nuget.org/packages/ChromeHtmlToPdf

**Comment by MaceWindu** [comment]
4.2.2 released 9/03 and doesn't include this PR

**Comment by Sicos1977** [comment]
Check,.... I will make a new release

**Comment by Sicos1977** [comment]
Done

**Pull request merged**
